name: 'Continuous Integration'
on:
  push:
    branches: [master]
  release:
    types: [published]

jobs:
  build_docker:
    runs-on: ubuntu-latest
    name: "Build Kafka-Proxy image"
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v2

      - name: "Login"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Publish to Docker Hub"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: shmel1k/kafka-proxy:latest
