name: 'Continuous Integration'
on:
  push:
    tags:
      - v*

jobs:
  build_docker:
    runs-on: ubuntu-latest
    name: "Build Kafka-Proxy image"
    steps:
      - name: Get the tag
        uses: dawidd6/action-get-tag@v1
        id: get_tag
      - name: "Check out repository"
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.get_tag.outputs.tag }}
      - name: "Login"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "Publish to Docker Hub"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: citymobil/kafka-proxy:${{ steps.get_tag.outputs.tag }}
